FROM flink:1.7.1-scala_2.12

# Add Prometheus, Table and Queryable state jars. Add additional jars if you need
RUN mv /opt/flink/opt/flink-metrics-prometheus-1.7.1.jar /opt/flink/lib/
RUN mv /opt/flink/opt/flink-queryable-state-runtime_2.12-1.7.1.jar /opt/flink/lib/
RUN mv /opt/flink/opt/flink-table_2.12-1.7.1.jar /opt/flink/lib/

# Update entrypoint
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh /